# Generated by Django 4.2.11 on 2024-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='statuts',
            new_name='status',
        ),
    ]
